baseURL = 'https://lennymartinez.com/'
languageCode = 'en-US'
title = 'Lenny Martinez'

defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]

[params]
currentTag = "PhD Candidate at [ISIR](https://www.isir.upmc.fr/)."
description = "Hey!👋🏽 I'm Lenny Martinez, a designer and researcher. I'm currently working on my PhD in Human-Computer Interaction at ISIR in Paris, France."
contactEmail = "lenny.martinez@isir.upmc.fr"
github = "https://github.com/lennymd"
instagram = "https://instagram.com/lennyisnoticing"
linkedin = "https://www.linkedin.com/in/lennymartinezd/"
scholar = "https://scholar.google.com/citations?hl=en&user=sEuQs7wAAAAJ"

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Projects"
pageRef = "/projects"
weight = 20
[[menu.main]]
name = "Teaching"
pageRef = "/teaching"
weight = 30

[minify]
disableXML = true
[minify.tdewolff]
[minify.tdewolff.html]
keepWhitespace = false
keepComments = false

[markup]
[markup.goldmark]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
title = true
