baseURL = 'https://lennymartinez.com/'
title = 'Lenny Martinez'
defaultContentLanguage = 'en'
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true

[languages.en]
label = 'English'
locale = 'en-US'
direction = 'ltr'

[params]
description = '''Hey!👋🏽 I'm Lenny Martinez, a designer and researcher. I'm currently working on my PhD in Human-Computer Interaction at ISIR in Paris, France.'''
shortBio = '''PhD Candidate at [ISIR](https://www.isir.upmc.fr/).'''
contactEmail = 'lenny.martinez@isir.upmc.fr'
images = ['img/lennymartinez.jpg']

[params.meta]
themeColor = '#d49f50'
backgroundColor = '#1a1a1a'
ogImageAlt = 'Lenny Martinez'

[[params.social]]
name = 'Instagram'
url = 'https://instagram.com/lennyisnoticing'
inFooter = true

[[params.social]]
name = 'LinkedIn'
url = 'https://www.linkedin.com/in/lennymartinezd/'
inFooter = true

[[params.social]]
name = 'GitHub'
url = 'https://github.com/lennymd'
inFooter = true

[[params.social]]
name = 'Google Scholar'
url = 'https://scholar.google.com/citations?hl=en&user=sEuQs7wAAAAJ'
inFooter = false


[menu]
[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10
[[menu.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20
[[menu.main]]
name = 'CV'
pageRef = '/cv'
weight = 30

[minify]
disableXML = true

[imaging]
resampleFilter = 'Lanczos'
[imaging.jpeg]
quality = 85
[imaging.webp]
quality = 80


[markup]
[markup.goldmark]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
title = true
