baseURL = 'https://lennymartinez.com/'
title = 'Lenny Martinez'
defaultContentLanguage = 'en'
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true

[languages.en]
label = 'English'
locale = 'en-US'
direction = 'ltr'

[params]
description = '''Hey! I'm Lenny Martinez, a designer and researcher. I'm currently working on my PhD in Human-Computer Interaction at ISIR in Paris, France.'''
contactEmail = 'lenny.martinez@isir.upmc.fr'
images = ['img/lennymartinez.jpg']

[params.meta]
themeColor = '#115545'
backgroundColor = '#fff'
ogImageAlt = 'Lenny Martinez'


[menu]
[[menu.main]]
name = 'Publications'
pageref = '/publications'
weight = 10
[[menu.main]]
name = 'Work'
pageRef = '/projects'
weight = 20
[[menu.main]]
name = 'Teaching'
pageRef = '/teaching'
weight = 30

[minify]
disableXML = true

[imaging]
resampleFilter = 'Lanczos'
[imaging.jpeg]
quality = 85
[imaging.webp]
quality = 80


[markup]
[markup.goldmark]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
title = true
